services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=hrdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-container
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_PORT=9093
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_INTER_BROKER_PROTOCOL=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - backend_network

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zookeeper-container
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - backend_network

volumes:
  postgres_data:
    driver: local

networks:
  backend_network:
    driver: bridge
